/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domain.ui.user;

import domain.adapter.controller.board.create.CreateBoardController;
import domain.adapter.presenter.board.create.CreateBoardViewModel;
import domain.adapter.controller.board.findById.FindBoardByIdController;
import domain.adapter.presenter.board.findById.FindBoardByIdViewModel;
import domain.model.DomainEventBus;
import domain.ui.MainFrame;
import domain.usecase.repository.IBoardRepository;

import javax.swing.DefaultListModel;

/**
 *
 * @author lab1321
 */
public class UserPanel extends javax.swing.JPanel {
    private DomainEventBus eventBus;
    private MainFrame mainFrame;
    private DefaultListModel defaultListModel;
    private CreateBoardController createBoardController;
    private CreateBoardViewModel createBoardViewModel;
    private FindBoardByIdViewModel findBoardByIdViewModel;
    private FindBoardByIdController findBoardByIdController;
    private IBoardRepository boardRepository;

    /**
     * Creates new form board
     */
    public UserPanel(MainFrame mainFrame, IBoardRepository boardRepository, DomainEventBus eventBus) {
        this.boardRepository = boardRepository;
        this.eventBus = eventBus;
        this.createBoardController = new CreateBoardController();
        this.findBoardByIdController = new FindBoardByIdController();
        this.mainFrame = mainFrame;
        this.setBounds(0, 0, 1024, 768);
        defaultListModel = new DefaultListModel();
        initComponents();
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createBoardBtn = new javax.swing.JButton();
        myBoardLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myBoardList = new javax.swing.JList<>();
        userLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();

        createBoardBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        createBoardBtn.setText("Create Board");
        createBoardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBoardBtnActionPerformed(evt);
            }
        });

        myBoardLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        myBoardLabel.setText("My Board");

        myBoardList.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        myBoardList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myBoardListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(myBoardList);

        userLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        userLabel.setText("Teddy");

        userNameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        userNameLabel.setText("user name : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(myBoardLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(createBoardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(463, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(createBoardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userNameLabel)
                            .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addComponent(myBoardLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createBoardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBoardBtnActionPerformed
        // TODO add your handling code here:
        PopMenu popMenu = new PopMenu();
        myBoardList.setModel(defaultListModel);
        createBoardViewModel = createBoardController.createBoard(userLabel.getText(), popMenu.getIName(), boardRepository, eventBus);
        findBoardByIdViewModel = findBoardByIdController.findBoardById(createBoardViewModel.getBoardId(), boardRepository);
        defaultListModel.addElement(findBoardByIdViewModel.getName());
    }//GEN-LAST:event_createBoardBtnActionPerformed

    private void myBoardListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myBoardListMouseClicked
        // TODO add your handling code here:
        // switch panel
        mainFrame.getBoardPanel().setFindBoardByIdViewModel(findBoardByIdViewModel);
        
        mainFrame.getContentPane().remove(this);
        mainFrame.getContentPane().add(mainFrame.getBoardPanel());
        mainFrame.getBoardPanel().setVisible(true);
        mainFrame.revalidate();
        mainFrame.repaint();
    }//GEN-LAST:event_myBoardListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBoardBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel myBoardLabel;
    private javax.swing.JList<String> myBoardList;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
